{
 "title": "Disk Characteristics",
 "description": "Prometheus + node-exporter dashboard for viewing disk performance, utilization and saturation.",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "DataSource", "label": "Prometheus", "query": "prometheus" },
   {
    "name": "Node",
    "query": {
     "query": "label_values(node_time_seconds, instance)"
    }
   },
   {
    "name": "Disk",
    "query": {
     "query": "label_values(node_disk_write_time_seconds_total, device)"
    }
   },
   { "name": "RateInterval", "query": "2s,5s,15s,30s,1m,5m" }
  ]
 },
 "panels": [
  {
   "title": "EBS CloudWatch Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Volume IOPS Exceeded",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "{{VolumeId}}",
       "dimensions": { "InstanceId": "REDACTED_INSTANCE", "VolumeId": "REDACTED_VOL" },
       "metricName": "VolumeIOPSExceededCheck",
       "namespace": "AWS/EBS",
       "period": "1m",
       "region": "us-east-2",
       "statistics": [ "Sum" ]
      }
     ]
    },
    {
     "title": "Volume Throughput Exceeded",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "{{VolumeId}}",
       "dimensions": { "InstanceId": "REDACTED_INSTANCE", "VolumeId": "REDACTED_VOL" },
       "metricName": "VolumeThroughputExceededCheck",
       "namespace": "AWS/EBS",
       "region": "us-east-2",
       "statistics": [ "Average" ]
      }
     ]
    },
    {
     "title": "Volume Write Latency",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "alias": "{{VolumeId}}",
       "dimensions": { "InstanceId": "REDACTED_INSTANCE", "VolumeId": "REDACTED_VOL" },
       "metricName": "VolumeAvgWriteLatency",
       "namespace": "AWS/EBS",
       "period": "1m",
       "region": "us-east-2",
       "statistics": [ "Sum" ]
      }
     ]
    },
    {
     "title": "Volume Read Latency",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "alias": "{{VolumeId}}",
       "dimensions": { "InstanceId": "REDACTED_INSTANCE", "VolumeId": "REDACTED_VOL" },
       "metricName": "VolumeAvgReadLatency",
       "namespace": "AWS/EBS",
       "region": "us-east-2",
       "statistics": [ "Average" ]
      }
     ]
    },
    {
     "title": "EBS I/O Stalled",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 17 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "{{VolumeId}}",
       "dimensions": { "InstanceId": "REDACTED_INSTANCE", "VolumeId": "REDACTED_VOL" },
       "metricName": "VolumeStalledIOCheck",
       "namespace": "AWS/EBS",
       "period": "1m",
       "region": "us-east-2",
       "statistics": [ "Sum" ]
      }
     ]
    },
    {
     "title": "EC2 Attached EBS Check",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 17 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "dimensions": { "InstanceId": "REDACTED_INSTANCE" },
       "metricName": "StatusCheckFailed_AttachedEBS",
       "namespace": "AWS/EC2",
       "region": "us-east-2",
       "statistics": [ "Average" ]
      }
     ]
    }
   ]
  },
  {
   "title": "AWS EBS NVMe Log Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Read Latency",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "rate(read_seconds_total{instance=~\"$Node\", device!=\"sr0\", device=~\"$Disk\"}[$RateInterval])/rate(read_ops_total{instance=~\"$Node\", device!=\"sr0\", device=~\"$Disk\"}[$RateInterval])",
       "legendFormat": "{{device}} {{mount_path}} {{volume_id}}"
      }
     ]
    },
    {
     "title": "Write Latency",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "rate(write_seconds_total{instance=~\"$Node\", device!=\"sr0\", device=~\"$Disk\"}[$RateInterval])/rate(write_ops_total{instance=~\"$Node\", device!=\"sr0\", device=~\"$Disk\"}[$RateInterval])",
       "legendFormat": "{{device}} {{mount_path}} {{volume_id}}"
      }
     ]
    },
    {
     "title": "Read Latency P99",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum by(le, device, mount_path) (rate(read_io_latency_seconds_bucket{instance=~\"$Node\", device!=\"sr0\", device=~\"$Disk\"}[$RateInterval])))",
       "legendFormat": "{{device}} {{mount_path}} P99"
      },
      {
       "expr": "histogram_quantile(0.90, sum by(le, device, mount_path) (rate(read_io_latency_seconds_bucket{instance=~\"$Node\", device!=\"sr0\", device=~\"$Disk\"}[$RateInterval])))\r",
       "legendFormat": "{{device}} {{mount_path}} P90"
      }
     ]
    },
    {
     "title": "Write Latency P99",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum by(le, device, mount_path) (rate(write_io_latency_seconds_bucket{instance=~\"$Node\", device!=\"sr0\", device=~\"$Disk\"}[$RateInterval])))",
       "legendFormat": "{{device}} {{mount_path}} P99"
      },
      {
       "expr": "histogram_quantile(0.90, sum by(le, device, mount_path) (rate(write_io_latency_seconds_bucket{instance=~\"$Node\", device!=\"sr0\", device=~\"$Disk\"}[$RateInterval])))",
       "legendFormat": "{{device}} {{mount_path}} P90"
      }
     ]
    },
    {
     "title": "Read Throughput",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "rate(read_bytes_total{instance=~\"$Node\", device!=\"sr0\", device=~\"$Disk\"}[$RateInterval])\r",
       "legendFormat": "{{device}} {{mount_path}} {{volume_id}}"
      }
     ]
    },
    {
     "title": "Write Throughput",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "rate(write_bytes_total{instance=~\"$Node\", device!=\"sr0\", device=~\"$Disk\"}[$RateInterval])\r",
       "legendFormat": "{{device}} {{mount_path}} {{volume_id}}"
      }
     ]
    },
    {
     "title": "Read IOPS",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(read_ops_total{instance=~\"$Node\", device!=\"sr0\", device=~\"$Disk\"}[$RateInterval])\r",
       "legendFormat": "{{device}} {{mount_path}} {{volume_id}}"
      }
     ]
    },
    {
     "title": "Write IOPS",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(write_ops_total{instance=~\"$Node\", device!=\"sr0\", device=~\"$Disk\"}[$RateInterval])\r",
       "legendFormat": "{{device}} {{mount_path}} {{volume_id}}"
      }
     ]
    },
    {
     "title": "Read Size",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "rate(read_bytes_total{instance=~\"$Node\", device!=\"sr0\", device=~\"$Disk\"}[$RateInterval]) / rate(read_ops_total{instance=~\"$Node\", device!=\"sr0\", device=~\"$Disk\"}[$RateInterval])",
       "legendFormat": "{{device}} {{mount_path}} {{volume_id}}"
      }
     ]
    },
    {
     "title": "Write Size",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "rate(write_bytes_total{instance=~\"$Node\", device!=\"sr0\", device=~\"$Disk\"}[$RateInterval]) / rate(write_ops_total{instance=~\"$Node\", device!=\"sr0\", device=~\"$Disk\"}[$RateInterval])",
       "legendFormat": "{{device}} {{mount_path}} {{volume_id}}"
      }
     ]
    },
    {
     "title": "EBS Throughput Exceeded",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "rate(exceeded_tp_seconds_total{instance=~\"$Node\", device!=\"sr0\", device=~\"$Disk\"}[$RateInterval])",
       "legendFormat": "{{device}} {{mount_path}} {{volume_id}}"
      }
     ]
    },
    {
     "title": "EBS IOPS Exceeded",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 42 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "rate(exceeded_iops_seconds_total{instance=~\"$Node\", device!=\"sr0\", device=~\"$Disk\"}[$RateInterval])",
       "legendFormat": "{{device}} {{mount_path}} {{volume_id}}"
      }
     ]
    },
    {
     "title": "Instance Throughput Exceeded",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 50 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "rate(ec2_exceeded_tp_seconds_total{instance=~\"$Node\", device!=\"sr0\", device=~\"$Disk\"}[$RateInterval])\r",
       "legendFormat": "{{device}} {{mount_path}} {{volume_id}}"
      }
     ]
    },
    {
     "title": "Instance IOPS Exceeded",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 50 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "rate(ec2_exceeded_iops_seconds_total{instance=~\"$Node\", device!=\"sr0\", device=~\"$Disk\"}[$RateInterval])",
       "legendFormat": "{{device}} {{mount_path}} {{volume_id}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Linux OS Level Volume Performance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "IOPS",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 3 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(node_disk_writes_completed_total{instance=~\"$Node\", device!=\"sr0\", device=~\"$Disk\"}[$RateInterval]) + rate(node_disk_reads_completed_total{instance=~\"$Node\", device!=\"sr0\", device=~\"$Disk\"}[$RateInterval])",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "Total {{ instance }} {{ device }}",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "expr": "rate(node_disk_writes_completed_total{instance=~\"$Node\", device!=\"sr0\", device=~\"$Disk\"}[$RateInterval])",
       "legendFormat": "Write {{ instance }} {{ device }}"
      },
      {
       "expr": "rate(node_disk_reads_completed_total{instance=~\"$Node\", device!=\"sr0\", device=~\"$Disk\"}[$RateInterval])",
       "legendFormat": "Read {{ instance }} {{ device }}"
      }
     ]
    },
    {
     "title": "Disk I/O %util",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 3 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "rate(node_disk_io_time_seconds_total{instance=~\"$Node\", device!=\"sr0\", device=~\"$Disk\"}[$RateInterval])",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "{{ instance }} {{ device }}",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Average queue depth",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "short", "label": "I/O queue length" }
     ],
     "targets": [
      {
       "expr": "rate(node_disk_io_time_weighted_seconds_total{instance=~\"$Node\", device!=\"sr0\", device=~\"$Disk\"}[$RateInterval])",
       "legendFormat": "IO Queue Depth {{ device }} {{ instance }}"
      },
      {
       "expr": "rate(node_disk_write_time_seconds_total{instance=~\"$Node\", device!=\"sr0\", device=~\"$Disk\"}[$RateInterval])",
       "legendFormat": "Write Queue Depth {{ device }} {{ instance }}"
      },
      {
       "expr": "rate(node_disk_read_time_seconds_total{instance=~\"$Node\", device!=\"sr0\", device=~\"$Disk\"}[$RateInterval])",
       "legendFormat": "Read Queue Depth {{ device }} {{ instance }}"
      }
     ]
    },
    {
     "title": "Write latency",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 10 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "rate(node_disk_write_time_seconds_total{instance=~\"$Node\", device!=\"sr0\", device=~\"$Disk\"}[$RateInterval]) /  rate(node_disk_writes_completed_total{instance=~\"$Node\", device!=\"sr0\", device=~\"$Disk\"}[$RateInterval])",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "{{ instance }} {{ device }}",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Write bandwidth",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 17 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": " rate(node_disk_written_bytes_total{instance=~\"$Node\", device!=\"sr0\", device=~\"$Disk\"}[$RateInterval]) ",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "{{ instance }} {{ device }}",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Read latency",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 17 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "rate(node_disk_read_time_seconds_total{instance=~\"$Node\", device!=\"sr0\", device=~\"$Disk\"}[$RateInterval]) /  rate(node_disk_reads_completed_total{instance=~\"$Node\", device!=\"sr0\", device=~\"$Disk\"}[$RateInterval])",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "{{ instance }} {{ device }}",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Write size",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 24 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "rate(node_disk_written_bytes_total{instance=~\"$Node\", device!=\"sr0\", device=~\"$Disk\"}[$RateInterval]) / rate(node_disk_writes_completed_total{instance=~\"$Node\", device!=\"sr0\", device=~\"$Disk\"}[$RateInterval])",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "{{ instance }} {{ device }}",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Read bandwidth",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 24 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": " rate(node_disk_read_bytes_total{instance=~\"$Node\", device!=\"sr0\", device=~\"$Disk\"}[$RateInterval]) ",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "{{ instance }} {{ device }}",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "I/O adjacent merge",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 31 },
     "yaxes": [
      { "format": "short", "label": "Merged I/O number" }
     ],
     "targets": [
      {
       "expr": "rate(node_disk_reads_merged_total{instance=~\"$Node\", device!=\"sr0\", device=~\"$Disk\"}[$RateInterval])\r",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "Read merge {{instance}} {{device}}",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "expr": "rate(node_disk_writes_merged_total{instance=~\"$Node\", device!=\"sr0\", device=~\"$Disk\"}[$RateInterval])",
       "legendFormat": "Write merge {{instance}} {{device}}"
      }
     ]
    },
    {
     "title": "Read size",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 31 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "rate(node_disk_read_bytes_total{instance=~\"$Node\", device!=\"sr0\", device=~\"$Disk\"}[$RateInterval]) / rate(node_disk_reads_completed_total{instance=~\"$Node\", device!=\"sr0\", device=~\"$Disk\"}[$RateInterval])",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "{{ instance }} {{ device }}",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "AWS EBS NVMe Log Metrics (node_ebs prefix)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 }
  },
  {
   "title": "node_ebs Read Latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(node_ebs_read_seconds_total{instance=~\"$Node\", device!=\"sr0\", device=~\"$Disk\"}[$RateInterval])/rate(node_ebs_read_ops_total{instance=~\"$Node\", device!=\"sr0\", device=~\"$Disk\"}[$RateInterval])",
     "legendFormat": "{{device}} {{mount_path}} {{volume_id}}"
    }
   ]
  },
  {
   "title": "node_ebs Write Latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(node_ebs_write_seconds_total{instance=~\"$Node\", device!=\"sr0\", device=~\"$Disk\"}[$RateInterval])/rate(node_ebs_write_ops_total{instance=~\"$Node\", device!=\"sr0\", device=~\"$Disk\"}[$RateInterval])",
     "legendFormat": "{{device}} {{mount_path}} {{volume_id}}"
    }
   ]
  },
  {
   "title": "node_ebs Read Latency P99",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(le, device, mount_path) (rate(node_ebs_read_io_latency_seconds_bucket{instance=~\"$Node\", device!=\"sr0\", device=~\"$Disk\"}[$RateInterval])))",
     "legendFormat": "{{device}} {{mount_path}} P99"
    },
    {
     "expr": "histogram_quantile(0.90, sum by(le, device, mount_path) (rate(node_ebs_read_io_latency_seconds_bucket{instance=~\"$Node\", device!=\"sr0\", device=~\"$Disk\"}[$RateInterval])))\r",
     "legendFormat": "{{device}} {{mount_path}} P90"
    }
   ]
  },
  {
   "title": "node_ebs Write Latency P99",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(le, device, mount_path) (rate(node_ebs_write_io_latency_seconds_bucket{instance=~\"$Node\", device!=\"sr0\", device=~\"$Disk\"}[$RateInterval])))",
     "legendFormat": "{{device}} {{mount_path}} P99"
    },
    {
     "expr": "histogram_quantile(0.90, sum by(le, device, mount_path) (rate(node_ebs_write_io_latency_seconds_bucket{instance=~\"$Node\", device!=\"sr0\", device=~\"$Disk\"}[$RateInterval])))",
     "legendFormat": "{{device}} {{mount_path}} P90"
    }
   ]
  },
  {
   "title": "node_ebs Read Throughput",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rate(node_ebs_read_bytes_total{instance=~\"$Node\", device!=\"sr0\", device=~\"$Disk\"}[$RateInterval])\r",
     "legendFormat": "{{device}} {{mount_path}} {{volume_id}}"
    }
   ]
  },
  {
   "title": "node_ebs Write Throughput",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rate(node_ebs_write_bytes_total{instance=~\"$Node\", device!=\"sr0\", device=~\"$Disk\"}[$RateInterval])\r",
     "legendFormat": "{{device}} {{mount_path}} {{volume_id}}"
    }
   ]
  },
  {
   "title": "node_ebs Read Size",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "rate(node_ebs_read_bytes_total{instance=~\"$Node\", device!=\"sr0\", device=~\"$Disk\"}[$RateInterval]) / rate(node_ebs_read_ops_total{instance=~\"$Node\", device!=\"sr0\", device=~\"$Disk\"}[$RateInterval])",
     "legendFormat": "{{device}} {{mount_path}} {{volume_id}}"
    }
   ]
  },
  {
   "title": "node_ebs Write Size",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "rate(node_ebs_write_bytes_total{instance=~\"$Node\", device!=\"sr0\", device=~\"$Disk\"}[$RateInterval]) / rate(node_ebs_write_ops_total{instance=~\"$Node\", device!=\"sr0\", device=~\"$Disk\"}[$RateInterval])",
     "legendFormat": "{{device}} {{mount_path}} {{volume_id}}"
    }
   ]
  },
  {
   "title": "node_ebs Read IOPS",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(node_ebs_read_ops_total{instance=~\"$Node\", device!=\"sr0\", device=~\"$Disk\"}[$RateInterval])\r",
     "legendFormat": "{{device}} {{mount_path}} {{volume_id}}"
    }
   ]
  },
  {
   "title": "node_ebs Write IOPS",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(node_ebs_write_ops_total{instance=~\"$Node\", device!=\"sr0\", device=~\"$Disk\"}[$RateInterval])\r",
     "legendFormat": "{{device}} {{mount_path}} {{volume_id}}"
    }
   ]
  },
  {
   "title": "node_ebs EBS Throughput Exceeded",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 44 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(node_ebs_exceeded_tp_seconds_total{instance=~\"$Node\", device!=\"sr0\", device=~\"$Disk\"}[$RateInterval])",
     "legendFormat": "{{device}} {{mount_path}} {{volume_id}}"
    }
   ]
  },
  {
   "title": "node_ebs EBS IOPS Exceeded",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 44 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(node_ebs_exceeded_iops_seconds_total{instance=~\"$Node\", device!=\"sr0\", device=~\"$Disk\"}[$RateInterval])",
     "legendFormat": "{{device}} {{mount_path}} {{volume_id}}"
    }
   ]
  },
  {
   "title": "node_ebs Instance Throughput Exceeded",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 52 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(node_ebs_ec2_exceeded_tp_seconds_total{instance=~\"$Node\", device!=\"sr0\", device=~\"$Disk\"}[$RateInterval])\r",
     "legendFormat": "{{device}} {{mount_path}} {{volume_id}}"
    }
   ]
  },
  {
   "title": "node_ebs Instance IOPS Exceeded",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 52 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(node_ebs_ec2_exceeded_iops_seconds_total{instance=~\"$Node\", device!=\"sr0\", device=~\"$Disk\"}[$RateInterval])",
     "legendFormat": "{{device}} {{mount_path}} {{volume_id}}"
    }
   ]
  }
 ]
}