[package]
name = "s3tp"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "s3tp"
path = "main.rs"

[dependencies]
tokio = { version = "1", features = ["full"] }
reqwest = { version = "0.12", default-features = false, features = ["rustls-tls", "stream"] }
aws-config = "1"
aws-sdk-s3 = "1"
aws-credential-types = "1"
futures = "0.3"

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
